global(workDirectory="/run/rsyslog")

module(load="imudp")
module(load="imtcp")
module(load="ompipe")

input(type="imudp" port="10514")
input(type="imtcp" port="10514")

template(name="dblog" type="string" string="%fromhost-ip% %msg%\n")
action(type="ompipe" pipe="/run/rsyslog/devicelog.fifo" template="dblog")
